[package]
name = "ble-client"
version = "0.1.0"
edition = "2021"

[dependencies]
btleplug = "0.11.5"
chrono = "0.4.38"
futures = "0.3.30"
tokio = { version = "1.38.0", features = ["full"] }
uuid = "1.8.0"

