[target.riscv32imac-unknown-none-elf]
runner = "espflash flash --monitor"

[build]
target = "riscv32imac-unknown-none-elf"
rustflags = ["-C", "link-arg=-Tlinkall.x", "-C", "force-frame-pointers"]

[env]
ESP_LOG = "INFO"
